### ISSUE TITLE
[Task] Enhancement and optimization of "shenyu_execute_latency_millis_bucket" indicator item of metrics plug-in.

### ISSUE THREAD

**Issue by lianjunwei** [apache/shenyu#3399]
### Description

The current situation is:
shenyu_execute_latency_millis_bucket{le="0.005",} 3.0
shenyu_execute_latency_millis_bucket{le="0.01",} 3.0
shenyu_execute_latency_millis_bucket{le="0.025",} 3.0
shenyu_execute_latency_millis_bucket{le="0.05",} 3.0
shenyu_execute_latency_millis_bucket{le="0.075",} 3.0
shenyu_execute_latency_millis_bucket{le="0.1",} 3.0
shenyu_execute_latency_millis_bucket{le="0.25",} 3.0
shenyu_execute_latency_millis_bucket{le="0.5",} 3.0
shenyu_execute_latency_millis_bucket{le="0.75",} 3.0
shenyu_execute_latency_millis_bucket{le="1.0",} 1505.0
shenyu_execute_latency_millis_bucket{le="2.5",} 2351.0
shenyu_execute_latency_millis_bucket{le="5.0",} 3349.0
shenyu_execute_latency_millis_bucket{le="7.5",} 5243.0
shenyu_execute_latency_millis_bucket{le="10.0",} 8050.0
shenyu_execute_latency_millis_bucket{le="+Inf",} 26271.0
![image](https://user-images.githubusercontent.com/13819823/167899815-2c437132-f3fc-4271-b96d-c07c9530d026.png)

###  1. Add some time intervals.
   Because most request responses are more than 10ms. As shown in the picture above.
  will add：
le="20.0"
le="30.0"
le="40.0"
le="50.0"
le="70.0"
le="100.0"
le="150.0"
le="200.0"
le="250.0"
le="300.0"
le="400.0"
le="500.0"
le="600.0"
le="700.0"
le="800.0"
le="1000.0"
le="2000.0"
le="3000.0"
le="5000.0"
le="8000.0"
le="10000.0"
le="20000.0"
le="30000.0"
### 2. remove some time intervals.
**Because it is meaningless to count the delay below 1ms.**
{le="0.005",} 
{le="0.01",} 
{le="0.025",}
{le="0.05",} 
t{le="0.075",} 
{le="0.1",} 
{le="0.25",} 
{le="0.5",} 
{le="0.75",}

**Comment by dragon-zhang** [comment]
The unit of 0.005 is seconds, which means 5ms.






------------------ Original ------------------
From: lianjunwei ***@***.***&gt;
Date: Thu,May 12,2022 0:24 AM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Task] Enhancement and optimization of "shenyu_execute_latency_millis_bucket" indicator item of metrics plug-in. (Issue #3399)





 
Description
 
The current situation is:
 shenyu_execute_latency_millis_bucket{le="0.005",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.01",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.025",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.05",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.075",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.1",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.25",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.5",} 3.0
 shenyu_execute_latency_millis_bucket{le="0.75",} 3.0
 shenyu_execute_latency_millis_bucket{le="1.0",} 1505.0
 shenyu_execute_latency_millis_bucket{le="2.5",} 2351.0
 shenyu_execute_latency_millis_bucket{le="5.0",} 3349.0
 shenyu_execute_latency_millis_bucket{le="7.5",} 5243.0
 shenyu_execute_latency_millis_bucket{le="10.0",} 8050.0
 shenyu_execute_latency_millis_bucket{le="+Inf",} 26271.0
 
Task List
 
1. Add some time intervals.
 
Because most request responses are more than 10ms. As shown in the picture above.
 will add：
 le="15.0"
 le="20.0"
 le="25.0"
 le="30.0"
 le="40.0"
 le="50.0"
 le="70.0"
 le="100.0"
 le="150.0"
 le="200.0"
 le="250.0"
 le="300.0"
 le="400.0"
 le="500.0"
 le="600.0"
 le="700.0"
 le="800.0"
 le="1000.0"
 le="2000.0"
 le="3000.0"
 le="5000.0"
 le="8000.0"
 le="10000.0"
 le="20000.0"
 le="30000.0"
 
2. remove some time intervals.
 
Because it is meaningless to count the delay below 1ms.
 {le="0.005",}
 {le="0.01",}
 {le="0.025",}
 {le="0.05",}
 t{le="0.075",}
 {le="0.1",}
 {le="0.25",}
 {le="0.5",}
 {le="0.75",}

**Comment by lianjunwei** [comment]
> 
I also think the unit is seconds. However, according to the time consumption statistics of my printed logs, 95% of the requests take less than 1s, and the actual time consumption is inconsistent with the statistics returned by the metric interface.
If the unit is seconds, the number falling in the range of Le = "1.0" should be large.

**Comment by lianjunwei** [comment]
The statistics are weird. I continued to observe for some time.
