### ISSUE TITLE
[Question] How to use spring.profiles.active parameter to startup

### ISSUE THREAD

**Issue by MiracleDx** [apache/shenyu#3928]
### Question

This is how to startup in web site.
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/25627222/189070172-f442597e-e935-486e-bf00-62288127abc5.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/25627222/189070293-de05a672-654f-47cb-aebe-7d468fe6c331.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/25627222/189070395-460ac4c9-ac0b-4bd2-bda4-ec29c2931e9c.png">

like this, when I used this paramter, but it didn't active, it running with default profiles, I think in `start.sh` should has a paramter after `${MAIN_CLASS}`.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25627222/189070355-74986fac-dce4-4375-89d6-f1232d505508.png">

And, when I used this shell, I met a error of `The stack size specified is too small, Specify at least 384k`. so I edit `-Xss` to startup. It was my machine mistask?

**Comment by JooKS-me** [comment]
Sorry for my late reply.

The first question, I think there is a problem with our documents. If I want to use mysql or other databases, it is recommended to modify the configuration files in `conf/`.

The second problem, this is a problem caused by the environment, this is related to StackYellowPage, StackRedPage, StackShadowPage, OS page size and VM default page size(8k). Therefore, I suggest that in version 2.5.0 and earlier, according to your own env to modify the startup script according to the actual situation. After 2.5.1, the startup script will support customizing jvm parameters through environment variables.

**Comment by MiracleDx** [comment]
Thank for your replay.

About the first question I deineded variable of active profiles, and added this after `${MAIN_CLASS}` in `start.sh` to use different propertis file.
